In [1]:
import numpy as np
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score, f1_score

# --- CORE EVALUATION FUNCTION ---
def run_evaluation(label, y_true, y_pred):
    """
    Computes confusion matrix and metrics, including Specificity.
    """
    # 1. Generate Confusion Matrix
    matrix = confusion_matrix(y_true, y_pred)

    # Ensure we can handle cases where only one class is present
    if matrix.size == 4:
        tn, fp, fn, tp = matrix.ravel()
    else:
        # Fallback for edge cases where the matrix isn't 2x2
        tn = matrix[0,0] if y_true[0] == 0 else 0
        tp = matrix[0,0] if y_true[0] == 1 else 0
        fp = fn = 0

    # 2. Manual calculation for Specificity (TNR)
    # Formula: TN / (TN + FP)
    specificity = tn / (tn + fp) if (tn + fp) > 0 else 0

    # 3. Standard Metrics
    acc = accuracy_score(y_true, y_pred)
    pre = precision_score(y_true, y_pred, zero_division=0)
    rec = recall_score(y_true, y_pred, zero_division=0)
    f1  = f1_score(y_true, y_pred, zero_division=0)

    # 4. Output Results
    print(f"--- Scenario: {label} ---")
    print(f"Confusion Matrix:\n{matrix}")
    print(f"Accuracy:    {acc:.2f}")
    print(f"Precision:   {pre:.2f}")
    print(f"Recall (Sens): {rec:.2f}")
    print(f"Specificity: {specificity:.2f}")
    print(f"F1 Score:    {f1:.2f}")
    print("\n" + "="*30 + "\n")

# --- 10 NEW UNIQUE SCENARIOS ---
test_cases = [
    ("Heart Disease Check", ([1, 0, 1, 1, 0, 0, 1, 0], [1, 0, 1, 0, 0, 0, 1, 1])),
    ("Loan Approval Model", ([0, 1, 1, 0, 1, 0, 0], [0, 1, 0, 0, 1, 1, 0])),
    ("Email Spam Filter", ([1, 1, 0, 0, 1, 0, 1, 0], [1, 0, 0, 0, 1, 0, 1, 1])),
    ("Credit Card Fraud", ([1, 0, 0, 1, 0, 0, 0, 1, 0], [1, 0, 0, 1, 0, 1, 0, 0, 0])),
    ("Disease Diagnosis", ([0, 0, 1, 1, 1, 0, 1], [0, 1, 1, 0, 1, 0, 0])),
    ("Ad Click Prediction", ([1, 0, 1, 0, 1, 0], [1, 1, 1, 0, 0, 0])),
    ("Perfect Classification", ([1, 0, 1, 0, 1], [1, 0, 1, 0, 1])),
    ("Intrusion Detection", ([0, 0, 1, 0, 1, 1, 0], [0, 1, 1, 0, 0, 1, 0])),
    ("Student Pass/Fail", ([1, 1, 0, 1, 0, 0], [1, 0, 0, 1, 0, 1])),
    ("Network Failure Alert", ([0, 1, 0, 0, 0], [0, 0, 0, 0, 1]))
]

for name, (y_true, y_pred) in test_cases:
    run_evaluation(name, y_true, y_pred)

--- Scenario: Heart Disease Check ---
Confusion Matrix:
[[3 1]
 [1 3]]
Accuracy:    0.75
Precision:   0.75
Recall (Sens): 0.75
Specificity: 0.75
F1 Score:    0.75


--- Scenario: Loan Approval Model ---
Confusion Matrix:
[[3 1]
 [1 2]]
Accuracy:    0.71
Precision:   0.67
Recall (Sens): 0.67
Specificity: 0.75
F1 Score:    0.67


--- Scenario: Email Spam Filter ---
Confusion Matrix:
[[3 1]
 [1 3]]
Accuracy:    0.75
Precision:   0.75
Recall (Sens): 0.75
Specificity: 0.75
F1 Score:    0.75


--- Scenario: Credit Card Fraud ---
Confusion Matrix:
[[5 1]
 [1 2]]
Accuracy:    0.78
Precision:   0.67
Recall (Sens): 0.67
Specificity: 0.83
F1 Score:    0.67


--- Scenario: Disease Diagnosis ---
Confusion Matrix:
[[2 1]
 [2 2]]
Accuracy:    0.57
Precision:   0.67
Recall (Sens): 0.50
Specificity: 0.67
F1 Score:    0.57


--- Scenario: Ad Click Prediction ---
Confusion Matrix:
[[2 1]
 [1 2]]
Accuracy:    0.67
Precision:   0.67
Recall (Sens): 0.67
Specificity: 0.67
F1 Score:    0.67


--- Scenario: Pe